// <auto-generated />
namespace EAVEntities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EAV_Test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EAV_Test));
        
        string IMigrationMetadata.Id
        {
            get { return "201303291900126_EAV_Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
