// <auto-generated />
namespace EAVEntities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EAV_Test1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EAV_Test1));
        
        string IMigrationMetadata.Id
        {
            get { return "201303291903566_EAV_Test1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
