// <auto-generated />
namespace EAVEntities.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class eav : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eav));
        
        string IMigrationMetadata.Id
        {
            get { return "201306111546381_eav"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
