//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoEAVWeb {
    
    
    public partial class OneShotExample {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ctlSubjects control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlSubjects;
        
        /// <summary>
        /// ctlInstances control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlInstances;
        
        /// <summary>
        /// ctlSaveButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ctlSaveButton;
        
        /// <summary>
        /// ctlProjectContext control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVProjectContextControl ctlProjectContext;
        
        /// <summary>
        /// ctlSubjectContext control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVSubjectContextControl ctlSubjectContext;
        
        /// <summary>
        /// ctlContainerContext control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVContainerContextControl ctlContainerContext;
        
        /// <summary>
        /// ctlInstanceContext control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVInstanceContextControl ctlInstanceContext;
        
        /// <summary>
        /// ctlAttribute1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVTextBox ctlAttribute1;
        
        /// <summary>
        /// ctlAttribute2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVTextBox ctlAttribute2;
        
        /// <summary>
        /// ctlAttribute3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVTextBox ctlAttribute3;
        
        /// <summary>
        /// ctlAttribute4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVTextBox ctlAttribute4;
        
        /// <summary>
        /// ctlAttribute5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVTextBox ctlAttribute5;
    }
}
