//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoEAVWeb {
    
    
    public partial class RecurringExample {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ctlSubjects control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlSubjects;
        
        /// <summary>
        /// ctlInstances control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ctlInstances;
        
        /// <summary>
        /// ctlSaveButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ctlSaveButton;
        
        /// <summary>
        /// ctlProjectContext control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVProjectContextControl ctlProjectContext;
        
        /// <summary>
        /// ctlSubjectContext control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVSubjectContextControl ctlSubjectContext;
        
        /// <summary>
        /// ctlContainerContext control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVContainerContextControl ctlContainerContext;
        
        /// <summary>
        /// ctlInstanceContext control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVInstanceContextControl ctlInstanceContext;
        
        /// <summary>
        /// ctlValue1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVTextBox ctlValue1;
        
        /// <summary>
        /// ctlValue2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVTextBox ctlValue2;
        
        /// <summary>
        /// ctlValue3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVTextBox ctlValue3;
        
        /// <summary>
        /// ctlValue4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVTextBox ctlValue4;
        
        /// <summary>
        /// ctlValue5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVTextBox ctlValue5;
        
        /// <summary>
        /// ctlChildContainerContext1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVContainerContextControl ctlChildContainerContext1;
        
        /// <summary>
        /// ctlChildInstance1Repeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVInstanceContextRepeater ctlChildInstance1Repeater;
        
        /// <summary>
        /// ctlChildContainerContext2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVContainerContextControl ctlChildContainerContext2;
        
        /// <summary>
        /// ctlChildInstance2Repeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NeoEAV.Web.UI.EAVInstanceContextRepeater ctlChildInstance2Repeater;
    }
}
